// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AdminAuthGetNonceData, AdminAuthGetNonceErrors, AdminAuthGetNonceResponses, AdminAuthSignInData, AdminAuthSignInErrors, AdminAuthSignInResponses, AdminAuthVerifyData, AdminAuthVerifyErrors, AdminAuthVerifyResponses, AdminIcsFormsGetFormDetailData, AdminIcsFormsGetFormDetailErrors, AdminIcsFormsGetFormDetailResponses, AdminIcsFormsGetFormsListData, AdminIcsFormsGetFormsListErrors, AdminIcsFormsGetFormsListResponses, AdminIcsFormsUpdateFormData, AdminIcsFormsUpdateFormErrors, AdminIcsFormsUpdateFormResponses, AdminIdvtcFormsGetFormDetailData, AdminIdvtcFormsGetFormDetailErrors, AdminIdvtcFormsGetFormDetailResponses, AdminIdvtcFormsGetFormsListData, AdminIdvtcFormsGetFormsListErrors, AdminIdvtcFormsGetFormsListResponses, AdminIdvtcFormsUpdateFormData, AdminIdvtcFormsUpdateFormErrors, AdminIdvtcFormsUpdateFormResponses, AdminMembersGetMembersData, AdminMembersGetMembersErrors, AdminMembersGetMembersResponses, AdminMembersInitMembersData, AdminMembersInitMembersErrors, AdminMembersInitMembersResponses, AdminRotationRequestsGetDetailData, AdminRotationRequestsGetDetailErrors, AdminRotationRequestsGetDetailResponses, AdminRotationRequestsGetListData, AdminRotationRequestsGetListErrors, AdminRotationRequestsGetListResponses, AdminRotationRequestsPatchData, AdminRotationRequestsPatchErrors, AdminRotationRequestsPatchResponses, AdminUsersCreateUserData, AdminUsersCreateUserErrors, AdminUsersCreateUserResponses, AdminUsersGetUserDetailData, AdminUsersGetUserDetailErrors, AdminUsersGetUserDetailResponses, AdminUsersGetUsersListData, AdminUsersGetUsersListErrors, AdminUsersGetUsersListResponses, AdminUsersUpdateUserData, AdminUsersUpdateUserErrors, AdminUsersUpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const adminAuthGetNonce = <ThrowOnError extends boolean = false>(options?: Options<AdminAuthGetNonceData, ThrowOnError>): RequestResult<AdminAuthGetNonceResponses, AdminAuthGetNonceErrors, ThrowOnError> => (options?.client ?? client).get<AdminAuthGetNonceResponses, AdminAuthGetNonceErrors, ThrowOnError>({ url: '/admin/auth/nonce', ...options });

export const adminAuthSignIn = <ThrowOnError extends boolean = false>(options: Options<AdminAuthSignInData, ThrowOnError>): RequestResult<AdminAuthSignInResponses, AdminAuthSignInErrors, ThrowOnError> => (options.client ?? client).post<AdminAuthSignInResponses, AdminAuthSignInErrors, ThrowOnError>({
    url: '/admin/auth/signin',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const adminAuthVerify = <ThrowOnError extends boolean = false>(options?: Options<AdminAuthVerifyData, ThrowOnError>): RequestResult<AdminAuthVerifyResponses, AdminAuthVerifyErrors, ThrowOnError> => (options?.client ?? client).get<AdminAuthVerifyResponses, AdminAuthVerifyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/auth/verify',
    ...options
});

/**
 * Get paginated list of ICS forms with filters
 */
export const adminIcsFormsGetFormsList = <ThrowOnError extends boolean = false>(options?: Options<AdminIcsFormsGetFormsListData, ThrowOnError>): RequestResult<AdminIcsFormsGetFormsListResponses, AdminIcsFormsGetFormsListErrors, ThrowOnError> => (options?.client ?? client).get<AdminIcsFormsGetFormsListResponses, AdminIcsFormsGetFormsListErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/ics-forms',
    ...options
});

/**
 * Get detailed information about specific ICS form
 */
export const adminIcsFormsGetFormDetail = <ThrowOnError extends boolean = false>(options: Options<AdminIcsFormsGetFormDetailData, ThrowOnError>): RequestResult<AdminIcsFormsGetFormDetailResponses, AdminIcsFormsGetFormDetailErrors, ThrowOnError> => (options.client ?? client).get<AdminIcsFormsGetFormDetailResponses, AdminIcsFormsGetFormDetailErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/ics-forms/{id}',
    ...options
});

/**
 * Update ICS form review status and comments
 */
export const adminIcsFormsUpdateForm = <ThrowOnError extends boolean = false>(options: Options<AdminIcsFormsUpdateFormData, ThrowOnError>): RequestResult<AdminIcsFormsUpdateFormResponses, AdminIcsFormsUpdateFormErrors, ThrowOnError> => (options.client ?? client).patch<AdminIcsFormsUpdateFormResponses, AdminIcsFormsUpdateFormErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/ics-forms/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get paginated list of IDVTC forms with filters
 */
export const adminIdvtcFormsGetFormsList = <ThrowOnError extends boolean = false>(options?: Options<AdminIdvtcFormsGetFormsListData, ThrowOnError>): RequestResult<AdminIdvtcFormsGetFormsListResponses, AdminIdvtcFormsGetFormsListErrors, ThrowOnError> => (options?.client ?? client).get<AdminIdvtcFormsGetFormsListResponses, AdminIdvtcFormsGetFormsListErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/idvtc-forms',
    ...options
});

/**
 * Get detailed information about specific IDVTC form
 */
export const adminIdvtcFormsGetFormDetail = <ThrowOnError extends boolean = false>(options: Options<AdminIdvtcFormsGetFormDetailData, ThrowOnError>): RequestResult<AdminIdvtcFormsGetFormDetailResponses, AdminIdvtcFormsGetFormDetailErrors, ThrowOnError> => (options.client ?? client).get<AdminIdvtcFormsGetFormDetailResponses, AdminIdvtcFormsGetFormDetailErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/idvtc-forms/{id}',
    ...options
});

/**
 * Update IDVTC form review status and comments
 */
export const adminIdvtcFormsUpdateForm = <ThrowOnError extends boolean = false>(options: Options<AdminIdvtcFormsUpdateFormData, ThrowOnError>): RequestResult<AdminIdvtcFormsUpdateFormResponses, AdminIdvtcFormsUpdateFormErrors, ThrowOnError> => (options.client ?? client).patch<AdminIdvtcFormsUpdateFormResponses, AdminIdvtcFormsUpdateFormErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/idvtc-forms/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get active members for operator
 */
export const adminMembersGetMembers = <ThrowOnError extends boolean = false>(options: Options<AdminMembersGetMembersData, ThrowOnError>): RequestResult<AdminMembersGetMembersResponses, AdminMembersGetMembersErrors, ThrowOnError> => (options.client ?? client).get<AdminMembersGetMembersResponses, AdminMembersGetMembersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/operators/{nodeOperatorId}/members',
    ...options
});

/**
 * Admin-initialize members for an uninitialized operator (bypasses signatures + approval)
 */
export const adminMembersInitMembers = <ThrowOnError extends boolean = false>(options: Options<AdminMembersInitMembersData, ThrowOnError>): RequestResult<AdminMembersInitMembersResponses, AdminMembersInitMembersErrors, ThrowOnError> => (options.client ?? client).post<AdminMembersInitMembersResponses, AdminMembersInitMembersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/operators/{nodeOperatorId}/members/init',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get paginated list of rotation requests
 */
export const adminRotationRequestsGetList = <ThrowOnError extends boolean = false>(options?: Options<AdminRotationRequestsGetListData, ThrowOnError>): RequestResult<AdminRotationRequestsGetListResponses, AdminRotationRequestsGetListErrors, ThrowOnError> => (options?.client ?? client).get<AdminRotationRequestsGetListResponses, AdminRotationRequestsGetListErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/rotation-requests',
    ...options
});

/**
 * Get rotation request detail
 */
export const adminRotationRequestsGetDetail = <ThrowOnError extends boolean = false>(options: Options<AdminRotationRequestsGetDetailData, ThrowOnError>): RequestResult<AdminRotationRequestsGetDetailResponses, AdminRotationRequestsGetDetailErrors, ThrowOnError> => (options.client ?? client).get<AdminRotationRequestsGetDetailResponses, AdminRotationRequestsGetDetailErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/rotation-requests/{id}',
    ...options
});

/**
 * Approve or reject a rotation request
 */
export const adminRotationRequestsPatch = <ThrowOnError extends boolean = false>(options: Options<AdminRotationRequestsPatchData, ThrowOnError>): RequestResult<AdminRotationRequestsPatchResponses, AdminRotationRequestsPatchErrors, ThrowOnError> => (options.client ?? client).patch<AdminRotationRequestsPatchResponses, AdminRotationRequestsPatchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/rotation-requests/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get paginated list of admin users with filters
 */
export const adminUsersGetUsersList = <ThrowOnError extends boolean = false>(options?: Options<AdminUsersGetUsersListData, ThrowOnError>): RequestResult<AdminUsersGetUsersListResponses, AdminUsersGetUsersListErrors, ThrowOnError> => (options?.client ?? client).get<AdminUsersGetUsersListResponses, AdminUsersGetUsersListErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users',
    ...options
});

/**
 * Create new admin user
 */
export const adminUsersCreateUser = <ThrowOnError extends boolean = false>(options: Options<AdminUsersCreateUserData, ThrowOnError>): RequestResult<AdminUsersCreateUserResponses, AdminUsersCreateUserErrors, ThrowOnError> => (options.client ?? client).post<AdminUsersCreateUserResponses, AdminUsersCreateUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get detailed information about specific admin user
 */
export const adminUsersGetUserDetail = <ThrowOnError extends boolean = false>(options: Options<AdminUsersGetUserDetailData, ThrowOnError>): RequestResult<AdminUsersGetUserDetailResponses, AdminUsersGetUserDetailErrors, ThrowOnError> => (options.client ?? client).get<AdminUsersGetUserDetailResponses, AdminUsersGetUserDetailErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{id}',
    ...options
});

/**
 * Update admin user display name and/or active status
 */
export const adminUsersUpdateUser = <ThrowOnError extends boolean = false>(options: Options<AdminUsersUpdateUserData, ThrowOnError>): RequestResult<AdminUsersUpdateUserResponses, AdminUsersUpdateUserErrors, ThrowOnError> => (options.client ?? client).patch<AdminUsersUpdateUserResponses, AdminUsersUpdateUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
