// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type ApiErrorDetailDto = {
    /**
     * Field path this detail refers to (present for per-field validation errors).
     */
    field?: string;
    /**
     * Machine-readable sub-code for this detail (e.g. the failing validation rule).
     */
    code?: string;
    /**
     * Human-readable explanation of this detail.
     */
    message: string;
};

export type ApiErrorDto = {
    /**
     * Stable, machine-readable error code. Consumers switch on this rather than parsing `message`. See ERROR_CODES / GENERIC_ERROR_CODES for the published catalog.
     */
    code: string;
    /**
     * Human-readable English fallback message. Wording may change; do not parse it.
     */
    message: string;
    /**
     * Per-field details, populated for VALIDATION_FAILED and similar multi-field errors.
     */
    details?: Array<ApiErrorDetailDto>;
};

export type AdminAuthNonceDto = {
    /**
     * server-issued SIWE nonce to embed in the message
     */
    nonce: string;
};

export type AdminAuthPersonalSignDto = {
    /**
     * SIWE (Sign-In with Ethereum) message
     */
    message: string;
    /**
     * Cryptographic signature of SIWE message
     */
    signature: string;
};

export type AdminAuthSignInDto = {
    /**
     * JWT access token
     */
    access_token: string;
    /**
     * Token type
     */
    token_type: string;
    /**
     * Admin role
     */
    role: 'VIEWER' | 'REVIEWER' | 'SUPERVISOR';
};

export type AdminAuthPayloadDto = {
    /**
     * Admin Ethereum address
     */
    address: string;
    adminId: number;
    role: 'VIEWER' | 'REVIEWER' | 'SUPERVISOR';
};

export type IcsFormStatus = 'REVIEW' | 'APPROVED' | 'REJECTED';

export type IcsFormDataDto = {
    /**
     * Main Ethereum address
     */
    mainAddress: string;
    /**
     * Twitter message link
     */
    twitterLink?: string;
    /**
     * Discord message link
     */
    discordLink?: string;
    /**
     * Additional Ethereum addresses
     */
    additionalAddresses?: Array<string>;
};

export type IcsCommentsDto = {
    /**
     * Optional reason explaining why the form was rejected or other general review notes
     */
    reason?: string;
    /**
     * Review comment for main address field
     */
    mainAddress?: string;
    /**
     * Review comment for Twitter link field
     */
    twitterLink?: string;
    /**
     * Review comment for Discord link field
     */
    discordLink?: string;
    /**
     * Review comments for additional addresses, positionally aligned with the submitted addresses. An entry is null when that address has no comment.
     */
    additionalAddresses?: Array<string | null>;
};

export type IcsScoresDto = {
    /**
     * EthStaker solo-stakers list points
     */
    ethStaker?: number;
    /**
     * StakeCat solo-stakers list points
     */
    stakeCat?: number;
    /**
     * Obol Techne credential points
     */
    obolTechne?: number;
    /**
     * SSV Verified operators points
     */
    ssvVerified?: number;
    /**
     * CSM testnet participation points
     */
    csmTestnet?: number;
    /**
     * CSM mainnet participation points
     */
    csmMainnet?: number;
    /**
     * SDVTM testnet participation points
     */
    sdvtTestnet?: number;
    /**
     * SDVTM mainnet participation points
     */
    sdvtMainnet?: number;
    /**
     * Human passport points
     */
    humanPassport?: number;
    /**
     * Circles verification points
     */
    circles?: number;
    /**
     * Discord verification points
     */
    discord?: number;
    /**
     * X/Twitter verification points
     */
    twitter?: number;
    /**
     * SSV verified operators humanity points
     */
    ssvHumanity?: number;
    /**
     * Aragon votes participation points
     */
    aragonVotes?: number;
    /**
     * Snapshot votes participation points
     */
    snapshotVotes?: number;
    /**
     * Lido Galxe score points
     */
    lidoGalxe?: number;
    /**
     * Lido High Signal score points
     */
    highSignal?: number;
    /**
     * GitPOAPs points
     */
    gitPoaps?: number;
};

export type AdminIcsFormItemDto = {
    id: number;
    /**
     * Original submitted form data
     */
    form: IcsFormDataDto;
    /**
     * ICS form review status
     */
    status: IcsFormStatus;
    /**
     * Review comments for form fields
     */
    comments: IcsCommentsDto;
    /**
     * Calculated scores for scoring criteria
     */
    scores: IcsScoresDto;
    /**
     * Address of the last admin who reviewed this form
     */
    lastReviewer?: string | null;
    /**
     * Whether the proof has been issued. Once set to true, the review cannot be updated.
     */
    issued: boolean;
    /**
     * Whether this form is outdated (replaced by a newer submission for the same main address)
     */
    outdated: boolean;
    /**
     * Date when the form was submitted
     */
    createdAt: string;
    /**
     * Date when the review was last updated
     */
    updatedAt: string | null;
};

export type Pagination = {
    page: number;
    pageSize: number;
    itemCount: number;
    pageCount: number;
};

export type AdminIcsFormListResponseDto = {
    items: Array<AdminIcsFormItemDto>;
    pagination: Pagination;
};

export type AdminIcsFormDetailDto = {
    id: number;
    /**
     * Original submitted form data
     */
    form: IcsFormDataDto;
    /**
     * ICS form review status
     */
    status: IcsFormStatus;
    /**
     * Review comments for form fields
     */
    comments: IcsCommentsDto;
    /**
     * Calculated scores for scoring criteria
     */
    scores: IcsScoresDto;
    /**
     * Address of the last admin who reviewed this form
     */
    lastReviewer?: string | null;
    /**
     * Whether the proof has been issued. Once set to true, the review cannot be updated.
     */
    issued: boolean;
    /**
     * Whether this form is outdated (replaced by a newer submission for the same main address)
     */
    outdated: boolean;
    /**
     * Date when the form was submitted
     */
    createdAt: string;
    /**
     * Date when the review was last updated
     */
    updatedAt: string | null;
};

export type AdminIcsFormUpdateDto = {
    /**
     * New status for the form
     */
    status: IcsFormStatus;
    /**
     * Review comments for form fields
     */
    comments?: IcsCommentsDto;
    /**
     * Calculated scores for scoring criteria
     */
    scores?: IcsScoresDto;
    /**
     * Whether the proof has been issued. Can only be set to true for approved forms. Once set to true, the review cannot be updated.
     */
    issued?: boolean;
};

export type IdvtcFormStatus = 'REVIEW' | 'APPROVED' | 'REJECTED';

export type IdvtcClusterMemberDataDto = {
    /**
     * Cluster member Ethereum address
     */
    address: string;
    /**
     * Discord handle
     */
    discordHandle?: string;
    /**
     * Telegram username
     */
    telegramUsername?: string;
};

export type IdvtcFormDataDto = {
    /**
     * Main Ethereum address
     */
    mainAddress: string;
    /**
     * Discord message link
     */
    discordLink: string;
    /**
     * Telegram username
     */
    telegramUsername?: string;
    /**
     * Cluster members (addresses and contact info)
     */
    clusterMembers: Array<IdvtcClusterMemberDataDto>;
};

export type IdvtcCommentsDto = {
    /**
     * General review notes or rejection reason
     */
    reason?: string;
    /**
     * Review comment for main address
     */
    mainAddress?: string;
    /**
     * Review comment for Discord link
     */
    discordLink?: string;
    /**
     * Review comment for Telegram username
     */
    telegramUsername?: string;
    /**
     * Review comments for the 4 cluster members, positionally aligned. An entry is null when that member has no comment.
     */
    clusterMembers?: Array<string | null>;
};

export type AdminIdvtcFormItemDto = {
    id: number;
    /**
     * Original submitted form data
     */
    form: IdvtcFormDataDto;
    /**
     * IDVTC form review status
     */
    status: IdvtcFormStatus;
    /**
     * Review comments for form fields
     */
    comments: IdvtcCommentsDto;
    /**
     * Address of the last admin who reviewed this form
     */
    lastReviewer?: string | null;
    /**
     * Whether the proof has been issued (internal flag, admin-only)
     */
    issued: boolean;
    /**
     * Node operator this form has been bound to via members init; null when not yet bound
     */
    boundToNodeOperatorId?: string | null;
    /**
     * Whether this form is outdated (set automatically; cannot be changed by admins)
     */
    outdated: boolean;
    /**
     * Date when the form was submitted
     */
    createdAt: string;
    /**
     * Date when the review was last updated
     */
    updatedAt: string | null;
};

export type AdminIdvtcFormListResponseDto = {
    items: Array<AdminIdvtcFormItemDto>;
    pagination: Pagination;
};

export type AdminIdvtcFormDetailDto = {
    id: number;
    /**
     * Original submitted form data
     */
    form: IdvtcFormDataDto;
    /**
     * IDVTC form review status
     */
    status: IdvtcFormStatus;
    /**
     * Review comments for form fields
     */
    comments: IdvtcCommentsDto;
    /**
     * Address of the last admin who reviewed this form
     */
    lastReviewer?: string | null;
    /**
     * Whether the proof has been issued (internal flag, admin-only)
     */
    issued: boolean;
    /**
     * Node operator this form has been bound to via members init; null when not yet bound
     */
    boundToNodeOperatorId?: string | null;
    /**
     * Whether this form is outdated (set automatically; cannot be changed by admins)
     */
    outdated: boolean;
    /**
     * Date when the form was submitted
     */
    createdAt: string;
    /**
     * Date when the review was last updated
     */
    updatedAt: string | null;
};

export type AdminIdvtcFormUpdateDto = {
    /**
     * New status for the form. REVIEW keeps the form in review (e.g. saving comments without a final decision).
     */
    status: IdvtcFormStatus;
    /**
     * Review comments for form fields
     */
    comments?: IdvtcCommentsDto;
    /**
     * Whether the proof has been issued. Can only be set to true for approved forms.
     */
    issued?: boolean;
};

export type MemberDto = {
    /**
     * Member Ethereum address (lowercased)
     */
    address: string;
    discordHandle?: string | null;
    telegramUsername?: string | null;
};

export type ActiveMembersDto = {
    nodeOperatorId: string;
    members: [
        MemberDto,
        MemberDto,
        MemberDto,
        MemberDto
    ];
    createdAt: string;
    updatedAt: string;
};

export type AdminMembersResponseDto = {
    active?: ActiveMembersDto | null;
};

export type AdminInitMemberDto = {
    address: string;
    discordHandle?: string;
    telegramUsername?: string;
};

export type AdminInitMembersBodyDto = {
    members: [
        AdminInitMemberDto,
        AdminInitMemberDto,
        AdminInitMemberDto,
        AdminInitMemberDto
    ];
};

export type RotationRequestStatus = 'REVIEW' | 'APPROVED' | 'REJECTED';

export type ProposedSlotDto = {
    newAddress?: string | null;
    discordHandle?: string | null;
    telegramUsername?: string | null;
};

export type RotationRequestCommentsDto = {
    reason?: string | null;
    /**
     * Per-slot review comments (4), positionally aligned with slots. An entry is null when that slot has no comment.
     */
    slots: [
        string | null,
        string | null,
        string | null,
        string | null
    ];
};

export type AdminRotationRequestItemDto = {
    id: number;
    nodeOperatorId: string;
    submitterAddress: string;
    slots: [
        ProposedSlotDto,
        ProposedSlotDto,
        ProposedSlotDto,
        ProposedSlotDto
    ];
    status: RotationRequestStatus;
    superseded: boolean;
    comments: RotationRequestCommentsDto;
    lastReviewer?: string | null;
    reviewedAt?: string | null;
    createdAt: string;
    updatedAt: string;
};

export type AdminRotationRequestListResponseDto = {
    items: Array<AdminRotationRequestItemDto>;
    pagination: Pagination;
};

export type AdminRotationRequestDetailDto = {
    id: number;
    nodeOperatorId: string;
    submitterAddress: string;
    slots: [
        ProposedSlotDto,
        ProposedSlotDto,
        ProposedSlotDto,
        ProposedSlotDto
    ];
    status: RotationRequestStatus;
    superseded: boolean;
    comments: RotationRequestCommentsDto;
    lastReviewer?: string | null;
    reviewedAt?: string | null;
    createdAt: string;
    updatedAt: string;
};

export type AdminPatchRotationRequestDto = {
    status: RotationRequestStatus;
    comment?: string;
    slot1Comment?: string;
    slot2Comment?: string;
    slot3Comment?: string;
    slot4Comment?: string;
};

export type AdminUserItemDto = {
    /**
     * Admin user ID
     */
    id: number;
    /**
     * Ethereum address
     */
    address: string;
    /**
     * Display name for the admin user
     */
    name?: string | null;
    /**
     * Admin role
     */
    role: 'VIEWER' | 'REVIEWER' | 'SUPERVISOR';
    /**
     * Whether the admin user is active
     */
    active: boolean;
    /**
     * Date when the admin user was created
     */
    createdAt: string;
    /**
     * Date when the admin user was last updated
     */
    updatedAt: string;
};

export type AdminUserListResponseDto = {
    items: Array<AdminUserItemDto>;
    pagination: Pagination;
};

export type AdminUserDetailDto = {
    /**
     * Admin user ID
     */
    id: number;
    /**
     * Ethereum address
     */
    address: string;
    /**
     * Display name for the admin user
     */
    name?: string | null;
    /**
     * Admin role
     */
    role: 'VIEWER' | 'REVIEWER' | 'SUPERVISOR';
    /**
     * Whether the admin user is active
     */
    active: boolean;
    /**
     * Date when the admin user was created
     */
    createdAt: string;
    /**
     * Date when the admin user was last updated
     */
    updatedAt: string;
};

export type AdminUserCreateDto = {
    /**
     * Ethereum address of the new admin user
     */
    address: string;
    /**
     * Display name for the admin user
     */
    name?: string;
    /**
     * Role for the new admin user
     */
    role: 'VIEWER' | 'REVIEWER' | 'SUPERVISOR';
    /**
     * Whether the admin user should be active
     */
    active: boolean;
};

export type AdminUserUpdateDto = {
    /**
     * New display name for the admin user
     */
    name?: string;
    /**
     * Whether the admin user should be active
     */
    active?: boolean;
};

export type AdminAuthGetNonceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/auth/nonce';
};

export type AdminAuthGetNonceErrors = {
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminAuthGetNonceError = AdminAuthGetNonceErrors[keyof AdminAuthGetNonceErrors];

export type AdminAuthGetNonceResponses = {
    /**
     * issue a server-signed SIWE nonce to embed in the sign-in message
     */
    200: AdminAuthNonceDto;
};

export type AdminAuthGetNonceResponse = AdminAuthGetNonceResponses[keyof AdminAuthGetNonceResponses];

export type AdminAuthSignInData = {
    body: AdminAuthPersonalSignDto;
    path?: never;
    query?: never;
    url: '/admin/auth/signin';
};

export type AdminAuthSignInErrors = {
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminAuthSignInError = AdminAuthSignInErrors[keyof AdminAuthSignInErrors];

export type AdminAuthSignInResponses = {
    /**
     * Admin sign in with ethereum (SIWE) and return JWT
     */
    200: AdminAuthSignInDto;
};

export type AdminAuthSignInResponse = AdminAuthSignInResponses[keyof AdminAuthSignInResponses];

export type AdminAuthVerifyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/auth/verify';
};

export type AdminAuthVerifyErrors = {
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminAuthVerifyError = AdminAuthVerifyErrors[keyof AdminAuthVerifyErrors];

export type AdminAuthVerifyResponses = {
    /**
     * Verify admin JWT
     */
    200: AdminAuthPayloadDto;
};

export type AdminAuthVerifyResponse = AdminAuthVerifyResponses[keyof AdminAuthVerifyResponses];

export type AdminIcsFormsGetFormsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        pageSize?: number;
        /**
         * Filter by form status
         */
        status?: IcsFormStatus;
        /**
         * Filter by any address (main address or any additional address)
         */
        address?: string;
        /**
         * Filter forms submitted from this date (inclusive). Supports both YYYY-MM-DD and YYYY-MM-DDTHH:mm:ssZ formats
         */
        startDate?: string;
        /**
         * Filter forms submitted until this date (inclusive). Supports both YYYY-MM-DD and YYYY-MM-DDTHH:mm:ssZ formats
         */
        endDate?: string;
        /**
         * Filter by issued status
         */
        issued?: boolean;
        /**
         * Filter by outdated status
         */
        outdated?: boolean;
        /**
         * Field to sort by
         */
        sortBy?: 'id' | 'createdAt' | 'updatedAt' | 'mainAddress' | 'status' | 'issued' | 'outdated';
        /**
         * Sort order
         */
        sortOrder?: 'asc' | 'desc';
    };
    url: '/admin/ics-forms';
};

export type AdminIcsFormsGetFormsListErrors = {
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminIcsFormsGetFormsListError = AdminIcsFormsGetFormsListErrors[keyof AdminIcsFormsGetFormsListErrors];

export type AdminIcsFormsGetFormsListResponses = {
    /**
     * List of ICS forms with pagination
     */
    200: AdminIcsFormListResponseDto;
};

export type AdminIcsFormsGetFormsListResponse = AdminIcsFormsGetFormsListResponses[keyof AdminIcsFormsGetFormsListResponses];

export type AdminIcsFormsGetFormDetailData = {
    body?: never;
    path: {
        /**
         * ICS form ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/ics-forms/{id}';
};

export type AdminIcsFormsGetFormDetailErrors = {
    /**
     * ICS form not found
     */
    404: unknown;
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminIcsFormsGetFormDetailError = AdminIcsFormsGetFormDetailErrors[keyof AdminIcsFormsGetFormDetailErrors];

export type AdminIcsFormsGetFormDetailResponses = {
    /**
     * Detailed ICS form information
     */
    200: AdminIcsFormDetailDto;
};

export type AdminIcsFormsGetFormDetailResponse = AdminIcsFormsGetFormDetailResponses[keyof AdminIcsFormsGetFormDetailResponses];

export type AdminIcsFormsUpdateFormData = {
    body: AdminIcsFormUpdateDto;
    path: {
        /**
         * ICS form ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/ics-forms/{id}';
};

export type AdminIcsFormsUpdateFormErrors = {
    /**
     * ICS form not found
     */
    404: unknown;
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminIcsFormsUpdateFormError = AdminIcsFormsUpdateFormErrors[keyof AdminIcsFormsUpdateFormErrors];

export type AdminIcsFormsUpdateFormResponses = {
    /**
     * Updated ICS form information
     */
    200: AdminIcsFormDetailDto;
};

export type AdminIcsFormsUpdateFormResponse = AdminIcsFormsUpdateFormResponses[keyof AdminIcsFormsUpdateFormResponses];

export type AdminIdvtcFormsGetFormsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        pageSize?: number;
        /**
         * Filter by form status
         */
        status?: IdvtcFormStatus;
        /**
         * Filter by any address (main address or any cluster member address)
         */
        address?: string;
        /**
         * Filter by exact Discord link match (case-insensitive). Matches main discord link or any cluster member discord handle.
         */
        discordLink?: string;
        /**
         * Filter by exact Telegram username match (case-insensitive). Matches main telegram username or any cluster member telegram username.
         */
        telegramUsername?: string;
        /**
         * Filter forms submitted from this date (inclusive)
         */
        startDate?: string;
        /**
         * Filter forms submitted until this date (inclusive)
         */
        endDate?: string;
        /**
         * Filter by issued status
         */
        issued?: boolean;
        /**
         * Filter by outdated status
         */
        outdated?: boolean;
        /**
         * Field to sort by
         */
        sortBy?: 'id' | 'createdAt' | 'updatedAt' | 'mainAddress' | 'status' | 'issued' | 'outdated';
        /**
         * Sort order
         */
        sortOrder?: 'asc' | 'desc';
    };
    url: '/admin/idvtc-forms';
};

export type AdminIdvtcFormsGetFormsListErrors = {
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminIdvtcFormsGetFormsListError = AdminIdvtcFormsGetFormsListErrors[keyof AdminIdvtcFormsGetFormsListErrors];

export type AdminIdvtcFormsGetFormsListResponses = {
    /**
     * List of IDVTC forms with pagination
     */
    200: AdminIdvtcFormListResponseDto;
};

export type AdminIdvtcFormsGetFormsListResponse = AdminIdvtcFormsGetFormsListResponses[keyof AdminIdvtcFormsGetFormsListResponses];

export type AdminIdvtcFormsGetFormDetailData = {
    body?: never;
    path: {
        /**
         * IDVTC form ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/idvtc-forms/{id}';
};

export type AdminIdvtcFormsGetFormDetailErrors = {
    /**
     * IDVTC form not found
     */
    404: unknown;
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminIdvtcFormsGetFormDetailError = AdminIdvtcFormsGetFormDetailErrors[keyof AdminIdvtcFormsGetFormDetailErrors];

export type AdminIdvtcFormsGetFormDetailResponses = {
    /**
     * Detailed IDVTC form information
     */
    200: AdminIdvtcFormDetailDto;
};

export type AdminIdvtcFormsGetFormDetailResponse = AdminIdvtcFormsGetFormDetailResponses[keyof AdminIdvtcFormsGetFormDetailResponses];

export type AdminIdvtcFormsUpdateFormData = {
    body: AdminIdvtcFormUpdateDto;
    path: {
        /**
         * IDVTC form ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/idvtc-forms/{id}';
};

export type AdminIdvtcFormsUpdateFormErrors = {
    /**
     * IDVTC form not found
     */
    404: unknown;
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminIdvtcFormsUpdateFormError = AdminIdvtcFormsUpdateFormErrors[keyof AdminIdvtcFormsUpdateFormErrors];

export type AdminIdvtcFormsUpdateFormResponses = {
    /**
     * Updated IDVTC form information
     */
    200: AdminIdvtcFormDetailDto;
};

export type AdminIdvtcFormsUpdateFormResponse = AdminIdvtcFormsUpdateFormResponses[keyof AdminIdvtcFormsUpdateFormResponses];

export type AdminMembersGetMembersData = {
    body?: never;
    path: {
        nodeOperatorId: string;
    };
    query?: never;
    url: '/admin/operators/{nodeOperatorId}/members';
};

export type AdminMembersGetMembersErrors = {
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminMembersGetMembersError = AdminMembersGetMembersErrors[keyof AdminMembersGetMembersErrors];

export type AdminMembersGetMembersResponses = {
    200: AdminMembersResponseDto;
};

export type AdminMembersGetMembersResponse = AdminMembersGetMembersResponses[keyof AdminMembersGetMembersResponses];

export type AdminMembersInitMembersData = {
    body: AdminInitMembersBodyDto;
    path: {
        nodeOperatorId: string;
    };
    query?: never;
    url: '/admin/operators/{nodeOperatorId}/members/init';
};

export type AdminMembersInitMembersErrors = {
    /**
     * Already initialized / duplicate
     */
    400: unknown;
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminMembersInitMembersError = AdminMembersInitMembersErrors[keyof AdminMembersInitMembersErrors];

export type AdminMembersInitMembersResponses = {
    200: ActiveMembersDto;
};

export type AdminMembersInitMembersResponse = AdminMembersInitMembersResponses[keyof AdminMembersInitMembersResponses];

export type AdminRotationRequestsGetListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        status?: RotationRequestStatus;
        superseded?: boolean;
        nodeOperatorId?: string;
        /**
         * Match submitter or any proposed slot address
         */
        address?: string;
        startDate?: string;
        endDate?: string;
        sortBy?: 'id' | 'createdAt' | 'updatedAt' | 'reviewedAt' | 'nodeOperatorId' | 'status';
        sortOrder?: 'asc' | 'desc';
    };
    url: '/admin/rotation-requests';
};

export type AdminRotationRequestsGetListErrors = {
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminRotationRequestsGetListError = AdminRotationRequestsGetListErrors[keyof AdminRotationRequestsGetListErrors];

export type AdminRotationRequestsGetListResponses = {
    200: AdminRotationRequestListResponseDto;
};

export type AdminRotationRequestsGetListResponse = AdminRotationRequestsGetListResponses[keyof AdminRotationRequestsGetListResponses];

export type AdminRotationRequestsGetDetailData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/rotation-requests/{id}';
};

export type AdminRotationRequestsGetDetailErrors = {
    404: unknown;
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminRotationRequestsGetDetailError = AdminRotationRequestsGetDetailErrors[keyof AdminRotationRequestsGetDetailErrors];

export type AdminRotationRequestsGetDetailResponses = {
    200: AdminRotationRequestDetailDto;
};

export type AdminRotationRequestsGetDetailResponse = AdminRotationRequestsGetDetailResponses[keyof AdminRotationRequestsGetDetailResponses];

export type AdminRotationRequestsPatchData = {
    body: AdminPatchRotationRequestDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/rotation-requests/{id}';
};

export type AdminRotationRequestsPatchErrors = {
    404: unknown;
    /**
     * Request no longer actionable
     */
    409: unknown;
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminRotationRequestsPatchError = AdminRotationRequestsPatchErrors[keyof AdminRotationRequestsPatchErrors];

export type AdminRotationRequestsPatchResponses = {
    200: AdminRotationRequestDetailDto;
};

export type AdminRotationRequestsPatchResponse = AdminRotationRequestsPatchResponses[keyof AdminRotationRequestsPatchResponses];

export type AdminUsersGetUsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        pageSize?: number;
        /**
         * Filter by admin role
         */
        role?: 'VIEWER' | 'REVIEWER' | 'SUPERVISOR';
        /**
         * Filter by active status
         */
        active?: boolean;
        /**
         * Filter by admin address
         */
        address?: string;
        /**
         * Search by display name (case-insensitive substring match)
         */
        name?: string;
        /**
         * Field to sort by
         */
        sortBy?: 'id' | 'createdAt' | 'updatedAt' | 'address' | 'name' | 'role' | 'active';
        /**
         * Sort order
         */
        sortOrder?: 'asc' | 'desc';
    };
    url: '/admin/users';
};

export type AdminUsersGetUsersListErrors = {
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminUsersGetUsersListError = AdminUsersGetUsersListErrors[keyof AdminUsersGetUsersListErrors];

export type AdminUsersGetUsersListResponses = {
    /**
     * List of admin users with pagination
     */
    200: AdminUserListResponseDto;
};

export type AdminUsersGetUsersListResponse = AdminUsersGetUsersListResponses[keyof AdminUsersGetUsersListResponses];

export type AdminUsersCreateUserData = {
    body: AdminUserCreateDto;
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type AdminUsersCreateUserErrors = {
    /**
     * Invalid Ethereum address or validation error
     */
    400: unknown;
    /**
     * Admin user with this address already exists
     */
    409: unknown;
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminUsersCreateUserError = AdminUsersCreateUserErrors[keyof AdminUsersCreateUserErrors];

export type AdminUsersCreateUserResponses = {
    /**
     * Created admin user information
     */
    201: AdminUserDetailDto;
};

export type AdminUsersCreateUserResponse = AdminUsersCreateUserResponses[keyof AdminUsersCreateUserResponses];

export type AdminUsersGetUserDetailData = {
    body?: never;
    path: {
        /**
         * Admin user ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type AdminUsersGetUserDetailErrors = {
    /**
     * Admin user not found
     */
    404: unknown;
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminUsersGetUserDetailError = AdminUsersGetUserDetailErrors[keyof AdminUsersGetUserDetailErrors];

export type AdminUsersGetUserDetailResponses = {
    /**
     * Detailed admin user information
     */
    200: AdminUserDetailDto;
};

export type AdminUsersGetUserDetailResponse = AdminUsersGetUserDetailResponses[keyof AdminUsersGetUserDetailResponses];

export type AdminUsersUpdateUserData = {
    body: AdminUserUpdateDto;
    path: {
        /**
         * Admin user ID
         */
        id: number;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type AdminUsersUpdateUserErrors = {
    /**
     * Validation error or cannot deactivate current supervisor
     */
    400: unknown;
    /**
     * Admin user not found
     */
    404: unknown;
    /**
     * Error (ApiError envelope)
     */
    default: ApiErrorDto;
};

export type AdminUsersUpdateUserError = AdminUsersUpdateUserErrors[keyof AdminUsersUpdateUserErrors];

export type AdminUsersUpdateUserResponses = {
    /**
     * Updated admin user information
     */
    200: AdminUserDetailDto;
};

export type AdminUsersUpdateUserResponse = AdminUsersUpdateUserResponses[keyof AdminUsersUpdateUserResponses];
